apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eksnodegroups.aws.compute.hub.appvia.io
spec:
  group: aws.compute.hub.appvia.io
  names:
    kind: EKSNodeGroup
    listKind: EKSNodeGroupList
    plural: eksnodegroups
    singular: eksnodegroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EKSNodeGroup is the Schema for the eksnodegroups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EKSNodeGroupSpec defines the desired state of EKSNodeGroup
          properties:
            amitype:
              type: string
            clustername:
              type: string
            desiredsize:
              format: int64
              type: integer
            disksize:
              format: int64
              type: integer
            ec2sshkey:
              description: The security groups that are allowed SSH access (port 22)
                to the worker nodes
              type: string
            instancetypes:
              items:
                type: string
              type: array
            labels:
              additionalProperties:
                type: string
              type: object
            maxsize:
              format: int64
              type: integer
            minsize:
              format: int64
              type: integer
            nodegroupname:
              type: string
            noderole:
              type: string
            region:
              description: AWS region to launch node group within, must match the
                region of the cluster
              type: string
            releaseversion:
              type: string
            remoteaccess:
              type: string
            sourcesecuritygroups:
              description: The Amazon EC2 SSH key that provides access for SSH communication
                with the worker nodes in the managed node group https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
              items:
                type: string
              type: array
            subnets:
              items:
                type: string
              type: array
            tags:
              additionalProperties:
                type: string
              description: The metadata to apply to the node group
              type: object
            use:
              description: Use is a reference to an AWSCredentials object to use for
                authentication
              properties:
                group:
                  description: Group is the api group
                  type: string
                kind:
                  description: Kind is the name of the resource under the group
                  type: string
                name:
                  description: Name is name of the resource
                  type: string
                namespace:
                  description: Namespace is the location of the object
                  type: string
                version:
                  description: Version is the group version
                  type: string
              required:
              - group
              - kind
              - name
              - namespace
              - version
              type: object
            version:
              description: The Kubernetes version to use for your managed nodes
              type: string
          required:
          - clustername
          - nodegroupname
          - noderole
          - region
          - subnets
          - use
          type: object
        status:
          description: EKSNodeGroupStatus defines the observed state of EKSNodeGroup
          properties:
            status:
              description: Status provides a overall status
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
